# Generated by Django 4.1.4 on 2022-12-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'ordering': ('nome',), 'verbose_name': 'subcategoria', 'verbose_name_plural': 'subcategorias'},
        ),
    ]
